import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "./navigation";
import Footer from "./footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Foodieland",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="py-6 h-screen gap-16 flex flex-col ">
          <div className="hidden xl:block">
            <Navigation />
          </div>
          <div className="">{children}</div>
          <div className="hidden xl:block px-[68px]">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
